### ISSUE TITLE
ModuleNotFoundError: No module named 'airflow.providers.microsoft.powerbi'

### ISSUE THREAD

**Issue by g-t-hill** [ambika-garg/apache-airflow-microsoft-fabric-plugin#2]
This error is received when trying to use this plugin with a Fabric Data workflow.

`ModuleNotFoundError: No module named 'airflow.providers.microsoft.powerbi'`

**Comment by ambika-garg** [comment]
Can you share the DAG you are using to trigger the operator?

**Comment by g-t-hill** [comment]
Sure, I am trying to call a Pipeline in a Workspace - in my DAG I have the actual GUIDs of the Workspace and the Pipeline

```
from airflow import DAG
from apache_airflow_microsoft_fabric_plugin.operators.fabric import FabricRunItemOperator
from datetime import datetime

with DAG(
     dag_id="Run_Fabric_Item",
     schedule_interval='*/15 7-17 * * 1-5',
     start_date=datetime(2024, 7, 29),
     catchup=False,
) as dag:

     run_pipeline = FabricRunItemOperator(
         task_id="run_fabric_pipeline",
         workspace_id="xxxxxxx",
         item_id="xxxxxxx",
         fabric_conn_id="fabric_default",
         job_type="Pipeline",
         wait_for_termination=True,
         deferrable=True,
     )

     run_pipeline
```

**Comment by ambika-garg** [comment]
That's weird, I tried it again, its working properly. Can you share your logs?

**Comment by ambika-garg** [comment]
Hi @wezzAllinq & @g-t-hill,
Thank you for pointing out the issue. I’ve created a work item to address the bug and plan to have it fixed by early next week.
Kind regards, 
Ambika

**Comment by g-t-hill** [comment]
Great, thank you @ambika-garg - here is the log from my DAG run too in case it helps.
[dag_id=Run_Fabric_Item_run_id=manual__2024-07-31T14_04_38.329715+00_00_task_id=run_fabric_pipeline_attempt=1 (1).log](https://github.com/user-attachments/files/16559426/dag_id.Run_Fabric_Item_run_id.manual__2024-07-31T14_04_38.329715%2B00_00_task_id.run_fabric_pipeline_attempt.1.1.log)

**Comment by ambika-garg** [comment]
Hi @g-t-hill, import module bug has been fixed. If you have any further questions or require additional adjustments, please don’t hesitate to reach out.

Thank you!
Kind regards, 
Ambika

**Comment by g-t-hill** [comment]
Great, thank you - just tried it out and working! 😀
