### ISSUE TITLE
Refresh token needs client secret for authorization

### ISSUE THREAD

**Issue by wezzAllinq** [ambika-garg/apache-airflow-microsoft-fabric-plugin#3]
> Hey @domagoj-gusic-sb,
I noticed you created a separate package on PyPI: https://pypi.org/project/apache-airflow-microsoft-fabric-plugin-custom/. Could you please remove both the Power BI and Fabric plugins? They are misleading as I am actively managing these packages on behalf of Microsoft.
I would really appreciate it if you could raise a PR for any issues in the main repository. I’d be happy to review and merge your commits.
Thank you!

_Originally posted by @ambika-garg in https://github.com/ambika-garg/apache-airflow-microsoft-fabric-plugin/issues/1#issuecomment-2273786248_

Hey @ambika-garg, thank you for work on this package. The issue we had is that we cant use in our organization the authorization method without a client secret, in the package of @domagoj-gusic-sb  is it possible to use a client secret. And the authorization works like a charm. Any chance that is possible to add this to your package?

**Comment by domagoj-gusic-sb** [comment]
Hi,

I'm more than happy to delete both packages as I'm not really a fan of working like this, but at this time, this is the only way how we can fully utilize both plugins, and we need to utilize them "yesterday". Simply, we don't have the time to wait for few weeks/months for a fix. :(

In our company, we have very strict security policy and all user created apps require a client secret.

Moreover, there are two more issues, one with each plugin. First issue is with this plugin, for some reason, `location_id `of the URL of the job is not visible immediately and therefore, Airflow task will fail. Implementing 3 sleeps solved this temporarily. Next, there is unbounded local reference to a variable in PowerBI plugin which needed to be solved.

Hopefully you understand and thank you for the work on both of these plugins!

**Comment by ambika-garg** [comment]
Hi @domagoj-gusic-sb,

Thank you for your patience! We’ve now added support for the client secret in the plugin. With this update, you should be able to use this package independently, which should eliminate the need for any additional custom packages and simplify maintenance.

If you have any further questions or require additional adjustments, please don’t hesitate to reach out.

Kind regards,
Ambika
