### ISSUE TITLE
Invalid request. Request is malformed or invalid

### ISSUE THREAD

**Issue by PecTheFabricator** [ambika-garg/apache-airflow-microsoft-fabric-plugin#7]
Hi team,

First of all, thanks for this amazing connector.

I am facing some issues trying to configure the connector. I have followed all the steps mentioned in the doc, however I am always getting this error https://login.microsoftonline.com/error?code=9002313

Obs: 
I have generated the access token and used it locally to run the pipeline using the API and it worked.

**Comment by ambika-garg** [comment]
Hey @PecTheFabricator,
Could you share the link to the documentation you used? I’d like to check it out to help resolve the issue. In the meantime, could you also give this [solution](https://stackoverflow.com/questions/56870805/invalid-request-request-is-malformed-or-invalid-while-getting-access-token-fro) a try?
Thanks!

**Comment by PecTheFabricator** [comment]
@ambika-garg I followed the steps in [here](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#refresh-the-access-token) 
The error I shared is happening after setting the configuration inside airflow and running the dag.

**Comment by ambika-garg** [comment]
Hi @PecTheFabricator,
It looks like you might be entering the `access_token` in the "Password" field when setting up the connection for the dag. However, as per the documentation, you should use the `refresh_token` in the connection form instead, since access tokens are short-lived.
Please try using the `refresh_token` and see if that resolves the issue.

kind regards, 
Ambika

**Comment by PecTheFabricator** [comment]
Hi @ambika-garg now it seems to be working. Probably I was copying an invalid refresh_token. 
Just a note, in the doc it says that the client_secret is optional, however, in my case, if I don't set it, it will not work as expected

**Comment by PecTheFabricator** [comment]
Got it. Another situation that I am facing is, the pipeline has successfully been executed, however, in airflow it still running and showing the run_status as "InProgress", however in MS Fabric I can see it as success.

**Comment by ambika-garg** [comment]
I think it might be due to the fact that xcoms are only updated on the start and end of the pipeline run, so there is delayed introduced in calling API.

**Comment by ambika-garg** [comment]
Hi @PecTheFabricator, if your issue has been resolved, please feel free to close it. Thanks!
